from __future__ import annotations

import inspect

import tidalapi

SURFACE: dict[type[object], tuple[set[str], set[str]]] = {
    tidalapi.Session: (
        {
            "album",
            "artist",
            "check_login",
            "explore",
            "folder",
            "for_you",
            "genres",
            "get_albums_by_barcode",
            "get_tracks_by_isrc",
            "get_user",
            "hires_page",
            "home",
            "local_genres",
            "mix",
            "mixes",
            "mixv2",
            "moods",
            "playlist",
            "search",
            "track",
            "video",
            "videos",
        },
        {
            "client_enable_hires",
            "convert_type",
            "get_link_login",
            "load_oauth_session",
            "load_session",
            "load_session_from_file",
            "login_oauth",
            "login_oauth_simple",
            "login_pkce",
            "login_session_file",
            "parse_album",
            "parse_artist",
            "parse_artists",
            "parse_folder",
            "parse_media",
            "parse_mix",
            "parse_playlist",
            "parse_track",
            "parse_v2_mix",
            "parse_video",
            "pkce_get_auth_token",
            "pkce_login_url",
            "process_auth_token",
            "process_link_login",
            "save_session_to_file",
            "token_refresh",
        },
    ),
    tidalapi.media.Track: (
        {"get_radio_mix", "get_stream", "get_track_radio", "get_url", "lyrics"},
        {"parse", "parse_media", "parse_track"},
    ),
    tidalapi.media.Video: (
        {"get_url", "image"},
        {"parse", "parse_media", "parse_video"},
    ),
    tidalapi.album.Album: (
        {"get_audio_resolution", "image", "items", "page", "review", "similar", "tracks", "video"},
        {"parse"},
    ),
    tidalapi.artist.Artist: (
        {
            "get_albums",
            "get_albums_ep_singles",
            "get_albums_other",
            "get_bio",
            "get_radio",
            "get_radio_mix",
            "get_similar",
            "get_top_tracks",
            "get_videos",
            "image",
            "page",
        },
        {"get_ep_singles", "get_other", "items", "parse_artist", "parse_artists"},
    ),
    tidalapi.playlist.Playlist: (
        {"get_items_count", "get_tracks_count", "image", "items", "tracks", "wide_image"},
        {"factory", "parse", "parse_factory", "tracks_paginated"},
    ),
    tidalapi.playlist.UserPlaylist: (
        {
            "add",
            "add_by_isrc",
            "clear",
            "delete",
            "delete_by_id",
            "edit",
            "get_items_count",
            "get_tracks_count",
            "image",
            "items",
            "merge",
            "move_by_id",
            "move_by_index",
            "move_by_indices",
            "remove_by_id",
            "remove_by_index",
            "remove_by_indices",
            "set_playlist_private",
            "set_playlist_public",
            "tracks",
            "wide_image",
        },
        {"factory", "parse", "parse_factory", "tracks_paginated"},
    ),
    tidalapi.user.Favorites: (
        {
            "add_album",
            "add_artist",
            "add_mixes",
            "add_playlist",
            "add_track",
            "add_track_by_isrc",
            "add_video",
            "albums",
            "artists",
            "get_albums_count",
            "get_artists_count",
            "get_playlists_count",
            "get_tracks_count",
            "get_videos_count",
            "mixes",
            "playlist_folders",
            "playlists",
            "remove_album",
            "remove_artist",
            "remove_folders_playlists",
            "remove_mixes",
            "remove_playlist",
            "remove_track",
            "remove_video",
            "tracks",
            "videos",
        },
        {
            "albums_paginated",
            "artists_paginated",
            "playlists_paginated",
            "tracks_paginated",
            "videos_paginated",
        },
    ),
    tidalapi.user.LoggedInUser: (
        {
            "create_folder",
            "create_playlist",
            "image",
            "playlist_and_favorite_playlists",
            "playlists",
            "public_playlists",
        },
        {"factory", "parse"},
    ),
    tidalapi.mix.Mix: ({"get", "image", "items"}, {"parse"}),
    tidalapi.mix.MixV2: ({"get", "image"}, {"parse"}),
    tidalapi.playlist.Folder: (
        {"add_items", "items", "move_items_to_folder", "move_items_to_root", "remove", "rename"},
        {"parse"},
    ),
    tidalapi.genre.Genre: ({"get_genres", "items"}, {"parse_genre", "parse_genres"}),
    tidalapi.page.Page: ({"get"}, {"next", "parse"}),
    tidalapi.page.PageCategory: (set(), {"parse", "show_more"}),
    tidalapi.page.PageCategoryV2: (
        set(),
        {"parse", "parse_item", "register_subclass", "view_all"},
    ),
    tidalapi.page.PageLink: ({"get"}, set()),
    tidalapi.media.Lyrics: (set(), {"parse"}),
    tidalapi.media.Stream: (
        {"get_audio_resolution"},
        {"get_manifest_data", "get_stream_manifest", "parse"},
    ),
}


def test_every_public_tidalapi_method_is_covered_or_explicitly_excluded() -> None:
    for cls, (covered, excluded) in SURFACE.items():
        actual = {
            name
            for name, value in inspect.getmembers(cls)
            if not name.startswith("_") and callable(value)
        }
        assert not covered & excluded, cls
        assert actual == covered | excluded, (
            cls,
            "unaccounted",
            sorted(actual - covered - excluded),
            "removed",
            sorted((covered | excluded) - actual),
        )
